### ISSUE TITLE
fully hide "meta data" from timeline

### ISSUE THREAD

**Issue by kimusan** [kode-team/mastodon.nvim#30]
The timeline is very bloated with information - even with some parts (meta data) being faded out. It would be nice if it could be configured what data it shows. 
Maybe also wrap long lines as default in the timeline view.

**Comment by kimusan** [comment]
for the latter it would simply be setting:

set wrap 
set linebreak

**Comment by malkoG** [comment]
**Inserting virtual text to each line is essential**, because it enables us to get **status's id** using `nvim_buf_get_extmarks` function. 
In my short research and experience, It was an only option.

First implementation was just leaving color of virtual text to be white, but it wasn't that readable. 
Trying any possible colors, and investigating all of highlight groups, finally I found a hightlight group `Whitespace`

According to [this documentation](https://neovim.io/doc/user/api.html#nvim_buf_set_extmark())
*Hiding metadata*  is possible, if we can specify highlight group that would be transparent for any colorschemes

**Comment by malkoG** [comment]
![스크린샷 2023-09-30 15-55-37](https://github.com/kode-team/mastodon.nvim/assets/2427963/2e441cd0-246f-43db-9573-192d1e897a91)


I think I finally resolved this issue. But, I can't assure.

**Comment by malkoG** [comment]
I tried several themes, it worked.

# Nordic
![스크린샷 2023-09-30 16-16-06](https://github.com/kode-team/mastodon.nvim/assets/2427963/b6f626c8-5769-4248-84dc-0e69a24d4a1d)

# Tokyonight
![스크린샷 2023-09-30 16-15-37](https://github.com/kode-team/mastodon.nvim/assets/2427963/e4642b30-dd33-4137-b58d-113dbecef5e1)


# Catppuccin
![스크린샷 2023-09-30 16-10-10](https://github.com/kode-team/mastodon.nvim/assets/2427963/885f91a7-ec91-455f-af9f-9271b13777c9)

# Melange
![스크린샷 2023-09-30 15-55-37](https://github.com/kode-team/mastodon.nvim/assets/2427963/3e587f52-68ac-41ab-8557-8c426acf0776)
